# Generated by Django 4.0.5 on 2022-06-30 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('cl_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('cl_image', models.FileField(upload_to='app/static/media/images')),
                ('cl_name', models.CharField(max_length=100)),
                ('cl_mobile', models.CharField(max_length=100)),
                ('cl_email', models.CharField(max_length=100)),
                ('cl_address', models.CharField(max_length=100)),
                ('cl_about', models.CharField(max_length=100)),
                ('cl_status', models.IntegerField(default=0)),
                ('cl_created_by', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CollegeRequest',
            fields=[
                ('cr_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('cr_name', models.CharField(max_length=100)),
                ('cr_email', models.CharField(max_length=100)),
                ('cr_mobile', models.CharField(max_length=100)),
                ('cr_message', models.CharField(max_length=100)),
                ('cr_status', models.IntegerField(default=0)),
                ('cr_created_by', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CollegeStaff',
            fields=[
                ('cs_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('cs_image', models.FileField(upload_to='app/static/media/images')),
                ('cs_name', models.CharField(max_length=100)),
                ('cs_department', models.CharField(max_length=100)),
                ('cs_designation', models.CharField(max_length=100)),
                ('cs_status', models.IntegerField(default=0)),
                ('cs_created_by', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('co_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('co_name', models.CharField(max_length=100)),
                ('co_status', models.IntegerField(default=0)),
                ('co_created_by', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CoursesDetails',
            fields=[
                ('cd_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('cd_college_name', models.CharField(max_length=100)),
                ('cd_college_email', models.CharField(max_length=100)),
                ('cd_name', models.CharField(max_length=100)),
                ('cd_fees', models.CharField(max_length=100)),
                ('cd_total_seats', models.CharField(max_length=100)),
                ('cd_status', models.IntegerField(default=0)),
                ('cd_created_by', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('rg_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('rg_name', models.CharField(max_length=100)),
                ('rg_mobile', models.CharField(max_length=100)),
                ('rg_email', models.CharField(max_length=100)),
                ('rg_password', models.CharField(max_length=100)),
                ('rg_address', models.CharField(default='', max_length=100)),
                ('rg_status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('un_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('un_image', models.FileField(upload_to='app/static/media/images')),
                ('un_name', models.CharField(max_length=100)),
                ('un_mobile', models.CharField(max_length=100)),
                ('un_email', models.CharField(max_length=100)),
                ('un_address', models.CharField(max_length=100)),
                ('un_total_college', models.CharField(max_length=100)),
                ('un_status', models.IntegerField(default=0)),
                ('un_created_by', models.CharField(max_length=100)),
            ],
        ),
    ]
