# Generated by Django 4.0.5 on 2022-07-01 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_university_un_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collegestaff',
            name='cs_image',
        ),
    ]
