# Generated by Django 4.0.5 on 2022-07-01 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_college_cl_university_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegerequest',
            name='cr_address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='collegerequest',
            name='cr_percentage',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='collegerequest',
            name='cr_previous_education',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='collegerequest',
            name='cr_year_passing',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='coursesdetails',
            name='cd_available_seats',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='collegerequest',
            name='cr_message',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='collegerequest',
            name='cr_status',
            field=models.CharField(default='Pending', max_length=100),
        ),
    ]
