# Generated by Django 4.0.5 on 2022-07-02 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_collegerequest_cr_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegerequest',
            name='cr_department',
            field=models.CharField(default='', max_length=100),
        ),
    ]
