# Generated by Django 4.0.5 on 2022-07-02 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_collegerequest_cr_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegerequest',
            name='cr_payment_status',
            field=models.CharField(default='Pending', max_length=100),
        ),
    ]
