# Generated by Django 4.0.5 on 2022-07-05 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_collegerequest_cr_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegerequest',
            name='cr_amount',
            field=models.CharField(default='5000', max_length=100),
        ),
    ]
