# Generated by Django 4.0.5 on 2022-07-08 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_cd_available_seats_coursesdetails_cd_available_seats_gov_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegerequest',
            name='cr_seat_type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
