# Generated by Django 4.0.5 on 2022-07-17 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_institution'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstituteStaff',
            fields=[
                ('is_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('is_name', models.CharField(max_length=100)),
                ('is_department', models.CharField(max_length=100)),
                ('is_designation', models.CharField(max_length=100)),
                ('is_status', models.IntegerField(default=0)),
                ('is_created_by', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionCourse',
            fields=[
                ('ic_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('ic_institute_name', models.CharField(max_length=100)),
                ('ic_fees', models.CharField(max_length=100)),
                ('ic_status', models.IntegerField(default=0)),
                ('ic_created_by', models.CharField(max_length=100)),
            ],
        ),
    ]
