# Generated by Django 4.0.5 on 2022-07-17 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_institutestaff_institutioncourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionRequest',
            fields=[
                ('ir_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('ir_name', models.CharField(max_length=100)),
                ('ir_email', models.CharField(max_length=100)),
                ('ir_mobile', models.CharField(max_length=100)),
                ('ir_address', models.CharField(default='', max_length=100)),
                ('ir_previous_education', models.CharField(default='', max_length=100)),
                ('ir_percentage', models.CharField(default='', max_length=100)),
                ('ir_year_passing', models.CharField(default='', max_length=100)),
                ('ir_message', models.CharField(default='', max_length=100)),
                ('ir_status', models.CharField(default='Pending', max_length=100)),
                ('ir_payment_status', models.CharField(default='Pending', max_length=100)),
                ('ir_department', models.CharField(default='', max_length=100)),
                ('ir_amount', models.CharField(default='5000', max_length=100)),
                ('ir_created_by', models.CharField(max_length=100)),
            ],
        ),
    ]
