# Generated by Django 4.0.5 on 2022-08-09 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_institutionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='cl_rank',
            field=models.CharField(default='', max_length=100),
        ),
    ]
