# Generated by Django 4.0.5 on 2022-08-09 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_college_cl_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='cl_naac',
            field=models.CharField(default='', max_length=100),
        ),
    ]
