# Generated by Django 4.0.5 on 2022-08-09 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_college_cl_naac'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('rv_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('rv_ap_id', models.CharField(max_length=100)),
                ('rv_name', models.CharField(max_length=100)),
                ('rv_email', models.CharField(max_length=100)),
                ('rv_message', models.CharField(max_length=100)),
                ('rv_rating', models.CharField(max_length=100)),
                ('rv_status', models.CharField(max_length=100)),
            ],
        ),
    ]
