# Generated by Django 4.0.6 on 2022-08-29 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_review_rv_cl_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutioncourse',
            name='ic_created_by',
            field=models.CharField(default='', max_length=100),
        ),
    ]
