# Generated by Django 4.1 on 2022-09-02 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_institutioncourse_ic_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminmaster',
            name='ad_key',
            field=models.CharField(default='', max_length=100),
        ),
    ]
